# set parameter sequences
library(gbPopMod)

g.p <- set_g_p()
names(g.p)[10:22]
p <- list(c("K", "all"), c("K", "WP"), c("K", "Opn"),
          "pr.s", 
          c("pr.f", "all"), c("pr.f", "WP"), c("pr.f", "Opn"),
          c("fec", "all"), c("fec", "WP"), c("fec", "Opn"),
          "age.f", 
          "pr.sb",
          c("pr.est", "all"), c("pr.est", "WP"), c("pr.est", "Opn"),
          "sdd.max", 
          "sdd.rate",
          "n.ldd",
          c("pr.eat", "all"), c("pr.eat", "WP"), c("pr.eat", "Opn"),
          c("bird.hab", "WP"), c("bird.hab", "Opn"),
          "pr.s.bird")

p.seq <- list(K_all=expand_LCs(param=p[[1]][1], LC=p[[1]][2], len_out=6,
                               lc.min=c(500, 10, 80, 200, 80, 80),
                               lc.max=c(800, 20, 120, 300, 120, 120)),
              K_WP=expand_LCs(param=p[[2]][1], LC=p[[2]][2], len_out=6,
                              lc.min=c(NA, NA, NA, 200, NA, NA),
                              lc.max=c(NA, NA, NA, 300, NA, NA)),
              K_Opn=expand_LCs(param=p[[3]][1], LC=p[[3]][2], len_out=6,
                               lc.min=c(500, NA, NA, NA, NA, NA),
                               lc.max=c(800, NA, NA, NA, NA, NA)),
              pr.s=expand_cnpy(Op=c(0.2, 0.9), Cl=c(0.2, 0.9), length_out=3),
              pr.f_all=expand_LCs(param=p[[5]][1], LC=p[[5]][2], len_out=6,
                                  lc.min=c(0.4, 0.2, 0.2, 0.2, 0.2, 0.2),
                                  lc.max=c(0.95, 0.5, 0.7, 0.9, 0.7, 0.7)),
              pr.f_WP=expand_LCs(param=p[[6]][1], LC=p[[6]][2], len_out=6,
                                 lc.min=c(NA, NA, NA, 0.2, NA, NA),
                                 lc.max=c(NA, NA, NA, 0.9, NA, NA)),
              pr.f_Opn=expand_LCs(param=p[[7]][1], LC=p[[7]][2], len_out=6,
                                  lc.min=c(0.4, NA, NA, NA, NA, NA),
                                  lc.max=c(0.95, NA, NA, NA, NA, NA)),
              fec_all=expand_LCs(param=p[[8]][1], LC=p[[8]][2], len_out=6,
                                 lc.min=c(100, 10, 10, 10, 10, 10),
                                 lc.max=c(300, 200, 60, 60, 60, 60)),
              fec_WP=expand_LCs(param=p[[9]][1], LC=p[[9]][2], len_out=6,
                                lc.min=c(NA, NA, NA, 10, NA, NA),
                                lc.max=c(NA, NA, NA, 60, NA, NA)),
              fec_Opn=expand_LCs(param=p[[10]][1], LC=p[[10]][2], len_out=6,
                                 lc.min=c(100, NA, NA, NA, NA, NA),
                                 lc.max=c(300, NA, NA, NA, NA, NA)),
              age.f=expand_cnpy(Op=c(3, 4), Cl=c(6, 7), length_out=3),
              pr.sb=seq(0.1, 0.8, length.out=6),
              pr.est_all=expand_LCs(param=p[[13]][1], LC=p[[13]][2], len_out=6,
                                    lc.min=rep(0.01, 6),
                                    lc.max=c(0.2, 0.1, 0.2, 0.2, 0.2, 0.2)),
              pr.est_WP=expand_LCs(param=p[[14]][1], LC=p[[14]][2], len_out=6,
                                   lc.min=c(NA, NA, NA, 0.01, NA, NA),
                                   lc.max=c(NA, NA, NA, 0.2, NA, NA)),
              pr.est_Opn=expand_LCs(param=p[[15]][1], LC=p[[15]][2], len_out=6,
                                    lc.min=c(0.01, NA, NA, NA, NA, NA),
                                    lc.max=c(0.2, NA, NA, NA, NA, NA)),
              sdd.max=round(seq(10, 20, length.out=6)),
              sdd.rate=seq(0.05, 0.8, length.out=6),
              n.ldd=round(seq(1, 6, length.out=6)),
              pr.eat_all=expand_LCs(param=p[[19]][1], LC=p[[19]][2], len_out=6,
                                    lc.min=rep(0.05, 6),
                                    lc.max=rep(0.5, 6)),
              pr.eat_WP=expand_LCs(param=p[[20]][1], LC=p[[20]][2], len_out=6,
                                   lc.min=c(NA, NA, NA, 0.05, NA, NA),
                                   lc.max=c(NA, NA, NA, 0.5, NA, NA)),
              pr.eat_Opn=expand_LCs(param=p[[21]][1], LC=p[[21]][2], len_out=6,
                                    lc.min=c(0.05, NA, NA, NA, NA, NA),
                                    lc.max=c(0.5, NA, NA, NA, NA, NA)),
              bird.hab_WP=expand_LCs(param=p[[22]][1], LC=p[[22]][2], len_out=6,
                                     lc.min=c(NA, NA, NA, 0.05, NA, NA),
                                     lc.max=c(NA, NA, NA, 0.5, NA, NA)),
              bird.hab_Opn=expand_LCs(param=p[[23]][1], LC=p[[23]][2], len_out=6,
                                      lc.min=c(0.05, NA, NA, NA, NA, NA),
                                      lc.max=c(0.5, NA, NA, NA, NA, NA)),
              pr.s.bird=seq(0.3, 0.8, length.out=6))

saveRDS(p, "hpc/p.rds")
saveRDS(p.seq, "hpc/p_seq.rds")
